# Generated by Django 5.0.2 on 2024-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_room_options_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
