def get_list_language(language: str) -> dict:
    if language == 'ukrainian':
        return UKRAINIAN
    elif language == 'russian':
        return RUSSIAN
    else:
        return ENGLISH


def set_language(request, language: str):
    request.session['language'] = language

RUSSIAN={
    'description': 'Описание',
    'pricedecreasing': 'Убыванию цены',
    'priceincrease': 'Возрастанию цены',
    'all': 'Все',
    'economy': 'Эконом',
    'standart': 'Стандарт',
    'lux': 'Люкс',
    'semidelux': 'Частино делюкс',
    'category': 'Категория',
    'tags': 'Теги',
    'image_tag': 'Есть изображение',
    'refrigerator_tag': 'Холодильник включен',
    'bathroom_tag': 'Ванная комната включена',
    'sortby': 'Упорядочить по',
    'signin': 'Выйти',
    'signup': 'Зарегестрироватся',
    'booking': 'Забронировать',
    'rooms': 'Комнаты',
    'logout': 'Выйти',
    'language': 'Языки',
    'current_lang': 'Русский',
    'english': 'Английский',
    'ukrainian': 'Украинский',
    'russian': 'Русский',
    'bookroom': 'Забронировать комнату',
    'roomfield': 'Номер комнаты',
    'startdate': 'Начало бронирования',
    'enddate': 'Конец бронирования',
    'submit': 'Отправить',
    'priore': 'Статус',
    'free': 'Свободная',
    'busy': 'Занятая',
    'location': 'Расположение',
    'capacity': 'Количество',
    'price': 'Цена',
    'number': 'Номеру',
    'username': 'Имя пользователя',
    'phone': 'Номер телефона',
    'search': 'Искать',
}

UKRAINIAN={
    'description': 'Опис',
    'pricedecreasing': 'Зменшенню ціни',
    'priceincrease': 'Зростанню ціни',
    'all': 'Усі',
    'category': 'Категорія',
    'economy': 'Економ',
    'standart': 'Стандарт',
    'lux': 'Люкс',
    'semidelux': 'Частково делюкс',
    'category': 'Категория',
    'tags': 'Теги',
    'image_tag': 'Є зображення',
    'refrigerator_tag': 'Холодильник в комплекті',
    'bathroom_tag': 'Ванна кімната включена',
    'sortby': 'Впорядкувати за',
    'signin': 'Увійти',
    'signup': 'Зареєструвати',
    'booking': 'Забронювати',
    'rooms': 'Кімнати',
    'logout': 'Вийти',
    'language': 'Мови',
    'current_lang': 'Українська',
    'english': 'Англійська',
    'ukrainian': 'Українська',
    'russian': 'Російська',
    'bookroom': 'Забронювати кімнати',
    'roomfield': 'Номер кімнати',
    'startdate': 'Початок бронювання',
    'enddate': 'Кінець бронювання',
    'submit': 'Відправити',
    'priore': 'Статус',
    'free': 'Вільна',
    'busy': 'Зайнята',
    'location': 'Розташування',
    'capacity': 'Кількість',
    'price': 'Ціна',
    'number': 'Номером',
    'username': 'Ім\'я користувача',
    'phone': 'Номер телефону',
    'search': 'Шукати',
}
ENGLISH={
    'description': 'Description',
    'pricedecreasing': 'Price Decreasing',
    'priceincrease': 'Price Increase',
    'all': 'All',
    'category': 'Category',
    'economy': 'Economy',
    'standart': 'Standart',
    'lux': 'Lux',
    'semidelux': 'Semi delux',
    'tags': 'Tags',
    'image_tag': 'Have image',
    'refrigerator_tag': 'Refrigerator included',
    'bathroom_tag': 'Bathroom included',
    'sortby': 'Sort by',
    'signin': 'sign in',
    'signup': 'sign up',
    'rooms': 'Rooms',
    'booking': 'Booking',
    'logout': 'Log out',
    'language': 'Language',
    'current_lang': 'English',
    'english': 'English',
    'russian': 'Russian',
    'ukrainian': 'Ukrainian',
    'bookroom': 'Book room',
    'roomfield': 'Room number',
    'startdate': 'Start date book',
    'enddate': 'End date book',
    'submit': 'Submit',
    'priore': 'Priore',
    'free': 'Free',
    'busy': 'Busy',
    'location': 'Location',
    'capacity': 'Capacity',
    'price': 'Price',
    'number': 'Number',
    'username': 'Username',
    'phone': 'Phone number',
    'search': 'Search',
}